import { chromium } from "playwright";
const b = await chromium.launch({ args: ["--use-gl=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"] });
const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
p.on("pageerror", e => console.log("[pageerror]", e.message.slice(0,200)));
await p.goto("http://localhost:3005/", { waitUntil: "domcontentloaded" });
await p.waitForTimeout(9000);
const a = await p.evaluate(() => ({ has: !!window.__lenis, animatedScroll: window.__lenis?.animatedScroll, targetScroll: window.__lenis?.targetScroll, opts: window.__lenis?.options?.smoothWheel }));
console.log("before:", JSON.stringify(a));
await p.evaluate(() => { window.__lenis.scrollTo(1200); });
await p.waitForTimeout(120);
console.log("120ms after lenis.scrollTo(1200):", await p.evaluate(() => Math.round(window.__lenis.animatedScroll)));
await p.waitForTimeout(1500);
console.log("1.6s after:", await p.evaluate(() => Math.round(window.__lenis.animatedScroll)));
await b.close();
