import { chromium } from "playwright";
const [w = "1920", h = "1080", port = "3000"] = process.argv.slice(2);
const browser = await chromium.launch({ args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"] });
const page = await browser.newPage({ viewport: { width: +w, height: +h } });
await page.goto(`http://localhost:${port}/`, { waitUntil: "domcontentloaded" });
await page.waitForFunction(() => window.__scrollScene === true, null, { timeout: 240000, polling: 500 });
await page.waitForFunction(() => { const t = getComputedStyle(document.querySelector("[data-hero-panel]").previousElementSibling).transform; return t === "none" || t === "matrix(1, 0, 0, 1, 0, 0)"; }, null, { timeout: 240000, polling: 1000 });
await page.evaluate(() => { window.scrollTo(0, Math.round((0.796 * 3.32 + 3) * window.innerHeight)); window.dispatchEvent(new Event("scroll")); });
await page.waitForTimeout(2500);
const m = await page.evaluate(() => {
  const lines = [...document.querySelectorAll('[data-reveal="slide"]')];
  const fs = parseFloat(getComputedStyle(lines[0]).fontSize);
  const rects = lines.map((el) => el.getBoundingClientRect());
  const widest = rects.reduce((a, r) => (r.width > a.width ? r : a), rects[0]);
  const oneLine = fs * 1.75 * 1.2;
  const wrapped = lines.filter((el, i) => rects[i].height > oneLine).map((el) => el.textContent.trim());
  const worstCentre = Math.max(...rects.map((r) => Math.abs((r.left + r.right) / 2 - innerWidth / 2)));
  return { W: innerWidth, fontPx: +fs.toFixed(1), widestPx: Math.round(widest.width), widestText: widest && lines[rects.indexOf(widest)].textContent.trim(), wrapped, worstCentreOffset: Math.round(worstCentre), overflowX: document.documentElement.scrollWidth - innerWidth };
});
console.log(JSON.stringify(m));
await browser.close();
