import { chromium } from "playwright";
import { writeFileSync } from "node:fs";
const [out = "tv", waitS = "45"] = process.argv.slice(2);
const browser = await chromium.launch({ args: ["--use-gl=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"] });
const page = await browser.newPage({ viewport: { width: 1280, height: 800 } });
await page.addInitScript(() => { window.__heroHold = true; });
page.on("pageerror", (e) => console.log("[pageerror]", e.message));
const url = process.env.DARK ? "http://localhost:3005/?tvDark=1" : process.env.FLARE ? "http://localhost:3005/?tvFlare=1" : "http://localhost:3005/";
await page.goto(url, { waitUntil: "domcontentloaded" });
await page.waitForTimeout(Number(waitS) * 1000);
const cdp = await page.context().newCDPSession(page);
const { data } = await cdp.send("Page.captureScreenshot", { format: "png", fromSurface: false });
writeFileSync(`${out}.png`, Buffer.from(data, "base64"));
await browser.close();
